import Footer from "./components/footer"
import Navbar from "./components/navbar"
import './globals.css'
import './homepage/homepage.css'
import './team/teampage.css'
import './gallery/gallerypage.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
